# Generated by Django 5.1.1 on 2024-09-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_cart_user_rename_name_products_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='username',
            new_name='prod_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='username',
            new_name='name',
        ),
    ]
